### ISSUE TITLE
Single domain setup with multiple locales

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [dachcom-digital/pimcore-i18n#121]
In Pimcore projects we often have a setup similar like this, just like in the pimcore demo:

- Only one domain, specified in pimcore system settings (no site is used)
- One specific default language (de in this example), that will be the base for translations
- The link `de` points at  the root document (id 1) wich will make it the main page for the default language
- Other languages get their own main pages

![image](https://user-images.githubusercontent.com/125017857/218756658-45b3f7f6-beec-446c-a9f7-418497a529d5.png)

If we install the bundle in such a projects we run into errors like this. The language is setup properly and defintion of zones are not possible, since we use no sites. 
![image](https://user-images.githubusercontent.com/125017857/218758838-6bc4e11e-d714-4a7c-8c2a-6d54bd540984.png)
![image](https://user-images.githubusercontent.com/125017857/218759024-18758313-0915-4116-b01c-09274dce13a4.png)

I've read all the documentation but either I don't understand it or I'm lacking some other important part. 

----

The goal in this setup also is to strip the locale fragment of the url in the default language (_domain.com/de/seite1 should be domain.com/seite1_). 

It seems that this could be possible with i18n: 
https://github.com/dachcom-digital/pimcore-i18n/blob/659498a45c4e5eb1901d1d9e74c8fab8ad68c380/docs/91_StaticRoutes.md?plain=1#L143-L148

But at another point we have the following conflicting convention in the docs: 
https://github.com/dachcom-digital/pimcore-i18n/blob/659498a45c4e5eb1901d1d9e74c8fab8ad68c380/docs/26_Languages.md?plain=1#L11

----

**Can you please confirm if such setup is possible with i18n or not?**

Thanks in advance! 😊

**Comment by studio1gmbh-pimcore** [comment]
@solverat 🏓 short feedback would be highly appreciated. Thank you.

**Comment by solverat** [comment]
Hey @studio1gmbh-pimcore. 

Yes, the setup you've described, is not possible with i18n. 

While it is true, that you're able to use it without the locale fragment, you're not allowed to mix them. 

So either 
- you use multiple sites with defined locale properties (then you're able to skip the locale part) 
- or you're using a single site (without locale property), but then you need to provide valid subpages (`en`, `de` → add locale fragment and those pages).

If you're able to change your setup (using a locale fragment in your routes all the time), i18n is the right tool for you.

**Comment by studio1gmbh-pimcore** [comment]
@solverat thanks for clarify!

For single domain environments we commited us to use the following solution: 

- Use only one site, which is the root document (ID 1)
- Specify domain, languages and default language in pimcore system settings
- Remove locale property from root document
- Setup individual document trees for each language
- Implement a redirect action for the root document (as fallback, in case the automatic i18n redirects will fail for any reason)

Once setup, i18n works like a charm.

**Comment by solverat** [comment]
Awesome, glad to hear!
