### ISSUE TITLE
Context in snippets

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-i18n#123]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently we do not have I18nContext in snippets.
It is not possible to use `i18n_current_context()` in snippets without creating the context manually.

Feature request: I18nContextAware flag for snippets.

**Comment by solverat** [comment]
Fixed with #128
