### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-i18n#171]
Dear Contributors, 

we're currently working on dual licensing this bundle (under GPLv3 and DCL [`DACHCOM Commerce License`]) to be compatible with Pimcore Enterprise and Professional. In order to do that, we need your approval (contributor license agreement). The agreement can be found here: https://github.com/dachcom-digital/pimcore-i18n/blob/master/CLA.md

We therefore kindly ask the following persons to sign the CLA by **writing the following sentence as a comment under this issue**:

`I have read the CLA Document and I hereby sign the CLA`

- [x] @pascalmoser
- [x] @scrummer
- [x] @BlackbitDevs
- [x] @Zodiarc
- [x] @benwalch
- [x] @alexej-d
- [x] @GALCF
- [x] @dlhck
- [x] @tomhatzer

**Comment by alexej-d** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dlhck** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tomhatzer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by scrummer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Zodiarc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BlackbitDevs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GALCF** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by solverat** [comment]
Thanks to all of you for your help! :heart:
