### ISSUE TITLE
Session causes non working full page cache

### ISSUE THREAD

**Issue by gahabkaFlorian** [dachcom-digital/pimcore-i18n#18]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

In Pimcore v5, I want to use the full page cache but I need a PHPSESSID cookie. This disables the cache with a message
“X-Pimcore-Output-Cache-Disable-Reason: Session in use”. (Repsonse Header)

If the i18n manager bundle is disables, the cache works properly and no "PHPSESSID" is available.

Is there a possibility to run the cache with this cookie?

**Comment by solverat** [comment]
I'm afraid that's not possible at the moment. The Session Bag is required by the `DetectorListener`. However, we could implement a disable/enable flag which allows you to pass a this service. You could try to override the `I18nBundle\Session\SessionConfigurator` and `I18nBundle\EventListener\DetectorListener` in the meantime.

**Comment by gahabkaFlorian** [comment]
It would be quite good if you could implement an option that disable/enable the service.
Because I need the full page cache, I would highly appreciate this option.
Overwriting the code is not an option for me at this moment.

**Comment by solverat** [comment]
This has been fixed in `2.4.1` and `3.1.0`.
