### ISSUE TITLE
[XLIFF-BUG]Export failed

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-i18n#25]
While exporting XLIFF got this error prompts

{"success":false,"message":"An exception has been thrown during the rendering of a template (\u0022context is not defined\u0022)."}

Timestamp: Tue Mar 26 2019 10:13:58 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | Internal Server Error
URL: /admin/translation/xliff-export
Method: POST
Message: An exception has been thrown during the rendering of a template ("context is not defined").

PLZ fix it as discussed solverat

**Comment by scrummer** [comment]
Not only XLIFF - word exports are affected as well.

**Comment by solverat** [comment]
Not reproducable on test environment. Maybe a project related thing.
