### ISSUE TITLE
Allow locale adjustment also on other requests than the master request

### ISSUE THREAD

**Issue by davidhoeck** [dachcom-digital/pimcore-i18n#51]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

When rendering for example the add to cart partial via `{{ render(path('coreshop_cart_add')) }}` it is not working because the locale does not get adjusted on child requests. Maybe we could implement a check if it is a frontend request instead of checking if it's a master request.

**Comment by solverat** [comment]
See https://github.com/dachcom-digital/pimcore-i18n/pull/53#issuecomment-589950085.
