### ISSUE TITLE
Support Symfony Routes

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-i18n#65]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Is [this](https://github.com/dachcom-digital/pimcore-i18n/blob/master/src/I18nBundle/EventListener/I18nStartupListener.php#L230-L232) something planned or even possible at all? Would be awesome to have nice looking locales for Symfony Routes as well. :)

**Comment by solverat** [comment]
Well, it has to be done at some point, right? 😄  I'm adding this to the new feature list.

**Comment by alexej-d** [comment]
@solverat hey, are you guys progressing on this feature? I'm in the progress of building a new site for a client and this would come in handily. Maybe I could even help?

**Comment by solverat** [comment]
What a refactor! Now his is possible on dev-master. Would love to hear some feedback before we're going to tag this!

https://github.com/dachcom-digital/pimcore-i18n/blob/master/docs/29_SymfonyRoutes.md
