### ISSUE TITLE
Improve redirects when country code is not set in user languages

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-i18n#67]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I18n is ignoring a user locale without country code (de), when the same locale ist set in Pimcore with country code (de_CH).

**Example 1:**

User locales: de_CH, en
Pimcore locales: de, en

Current and expected Behavior: i18n redirects to de (working with PR #63)

**Example 2:**

User locales: de, en
Pimcore locales: de_CH, en

Current behavior: i18n redirects to en (ignoring de_CH)
Expected behavior: Redirect to de_CH because user preferred language should have more priority.

**Comment by solverat** [comment]
Fixed with #68.
