### ISSUE TITLE
Dynamic Symfony Route Prefixes

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-i18n#93]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In the following case, how would you define a dynamic `path` prefix instead of `matching_route_key`? Would it even be possible?

```
/**
     * @Route("{path}/{title}~pr{object}", name="project-detail", defaults={"path"=""}, requirements={"path"=".*?", "title"="[\w-]+", "object"="\d+"})
     * @Template()
     *
     * @param Request $request
     *
     * @return array
     */
    public function detailAction(Request $request)
```

**Comment by scrummer** [comment]
Hi @alexej-d 

If I understood that correctly, this seems to be a bit out of i18n context. The only thing i18n does in this context is to find translatable route parameters.

**Comment by alexej-d** [comment]
Yeah, I figured @scrummer 😄 
I am just looking for a way to dynamically define the matching route keys, so my users can define them as a document property or something else.

**Comment by scrummer** [comment]
Yes, that's no longer i18n context. Guess you have to build your own workaround or create a pull-/feature-request for that.

~Jan
