### ISSUE TITLE
Double Domain in hreflang

### ISSUE THREAD

**Issue by cmaerz** [dachcom-digital/pimcore-i18n#95]
| Q                | A
| ---------------- | -----
| Bug report?      | ?
| Feature request? | no
| BC Break report? | no
| RFC?             |  no

Hey,

not really sure if this is a bug or a wrong configuration, but i search de documentation and didn't really find a solution.

I got multiple domains, configured as sites in Pimcore.
![image](https://user-images.githubusercontent.com/1479186/170232677-b68f09b2-278d-4128-b937-55dbbae030f1.png)

Hreflangs for the homepages are ok:
![image](https://user-images.githubusercontent.com/1479186/170232873-2903b2f2-10ab-4384-ae1f-067b4cebccb7.png)

But for subpages the "main domain" is always added:
![image](https://user-images.githubusercontent.com/1479186/170233438-650841ba-6e73-4ee6-ac6a-9d40361dd523.png)

And i have no idea why.

**Comment by solverat** [comment]
Could you please also post your `i18n` configuration please?

Also, the site configuration from your sites would be interessting: 
![image](https://user-images.githubusercontent.com/700119/213188188-dd963646-8821-49e2-b1bd-129686ca7e84.png)

**Comment by scrummer** [comment]
@cmaerz I'll close this one due to inactivity. If you still have trouble or find some additional information feel free to reopen this issue!

~Jan
