### ISSUE TITLE
Should x-default and alternate links be pushed via HTTP2?

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-i18n#97]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It looks like the generated x-default and alternate links are pushed as weblinks when weblinks and HTTP2 are activated. I do not think this is on purpose. These two lines [src/I18nBundle/EventListener/Frontend/HeadLinkListener.php#L72](https://github.com/dachcom-digital/pimcore-i18n/blob/master/src/I18nBundle/EventListener/Frontend/HeadLinkListener.php#L72) and [src/I18nBundle/EventListener/Frontend/HeadLinkListener.php#L76](https://github.com/dachcom-digital/pimcore-i18n/blob/master/src/I18nBundle/EventListener/Frontend/HeadLinkListener.php#L76) should add 'webLink' => false to the extra param.

Would you like me to open a PR?

**Comment by solverat** [comment]
@alexej-d mhm, that's interesting. Do you have any screenshot of the rendered link?

In my tests, the webLink attribute only get's applied, if the `webLink` explicitly has been set. 

Pimcore reference: 

https://github.com/pimcore/pimcore/blob/e1408784d9d00901b19dfdded1fd6025f47bf6a4/lib/Twig/Extension/Templating/Traits/WebLinksTrait.php#L85

**Comment by alexej-d** [comment]
Check the Chrome network inspection tab – these are the links that are pushed: ![image](https://user-images.githubusercontent.com/3934198/201850912-6ffccbba-048e-4e8f-adeb-77b6d14fd104.png)

**Comment by solverat** [comment]
@alexej-d, thanks! Still weird, in my case, no weblink will be pushed in the setup.

I tested the x-default link for example:
https://github.com/dachcom-digital/pimcore-i18n/blob/efaa274e3798919af5f1270308124e6dbfa01b39/src/I18nBundle/EventListener/Frontend/HeadLinkListener.php#L72

Still no preloaded link. If I'm adding the weblink attribute:

![image](https://user-images.githubusercontent.com/700119/201855890-8c4cf761-64e6-4d52-82a3-f121c0e7fca7.png)

than I'm also see the preloaded link:

![image](https://user-images.githubusercontent.com/700119/201856097-0dc1ec28-2530-48d5-af71-b711a99aeebb.png)

**Comment by solverat** [comment]
However, I don't think it is wrong to add this attribute, if it helps! A PR would be great!

**Comment by alexej-d** [comment]
@solverat did you set this config?

```
framework:
    web_link:
        enabled: true
```

I presume this is the reason for this behaviour.

**Comment by solverat** [comment]
@alexej-d: Yes, that's also enabled on my site.

**Comment by solverat** [comment]
Merged, thank you @alexej-d
